package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.domain.repository.CreateInvoiceRequestDomainRepository;
import com.probestack.forgestudio.design.exception.ApiException;
import com.probestack.forgestudio.design.logging.BusinessOperationEvent;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.CreateInvoiceRequest;
import com.probestack.forgestudio.design.model.Invoice;
import com.probestack.forgestudio.design.model.InvoiceLineItem;
import com.probestack.forgestudio.design.model.InvoiceListResponse;
import com.probestack.forgestudio.design.model.UpdateInvoiceRequest;
import java.lang.Class;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.System;
import java.lang.Void;
import java.lang.reflect.Method;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for CreateInvoiceRequest operations.
 *
 * <p>This service depends on a persistence-neutral domain repository port.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class InvoicesService {
    private final CreateInvoiceRequestDomainRepository createInvoiceRequestDomainRepository;

    private final BusinessOperationLogger businessOperationLogger;

    public InvoicesService(
            CreateInvoiceRequestDomainRepository createInvoiceRequestDomainRepository,
            BusinessOperationLogger businessOperationLogger) {
        this.createInvoiceRequestDomainRepository = createInvoiceRequestDomainRepository;
        this.businessOperationLogger = businessOperationLogger;
    }

    public ResponseEntity<Invoice> createInvoice(CreateInvoiceRequest createInvoiceRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // Save the entity to database
            ensureEntityId(createInvoiceRequest);
            CreateInvoiceRequest savedCreateInvoiceRequest = createInvoiceRequestDomainRepository.save(createInvoiceRequest);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("createInvoice")
                            .resource("CreateInvoiceRequest")
                            .action("CREATE")
                            .status("SUCCESS")
                            .repository("CreateInvoiceRequestDomainRepository")
                            .collection("invoice_billing_service_invoices")
                            .documentId(getEntityId(savedCreateInvoiceRequest))
                            .recordCount(1)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            Invoice response = mapToInvoice(savedCreateInvoiceRequest);
            return ResponseEntity.status(HttpStatus.CREATED).body(response);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("createInvoice")
                            .resource("CreateInvoiceRequest")
                            .action("CREATE")
                            .status("FAILED")
                            .repository("CreateInvoiceRequestDomainRepository")
                            .collection("invoice_billing_service_invoices")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_write_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<Invoice> getInvoiceById(String invoiceId) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve entity by ID from database
            String repositoryId = toRepositoryId(invoiceId);
            Optional<CreateInvoiceRequest> entity = createInvoiceRequestDomainRepository.findById(repositoryId);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getInvoiceById")
                            .resource("CreateInvoiceRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("CreateInvoiceRequestDomainRepository")
                            .collection("invoice_billing_service_invoices")
                            .documentId(repositoryId)
                            .recordCount(entity.isPresent() ? 1 : 0)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            return entity.map(this::mapToInvoice).map(ResponseEntity::ok).orElseThrow(() -> ApiException.notFound("CreateInvoiceRequest", repositoryId));
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getInvoiceById")
                            .resource("CreateInvoiceRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("CreateInvoiceRequestDomainRepository")
                            .collection("invoice_billing_service_invoices")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<InvoiceListResponse> listInvoices(String customerId, String status,
            Integer page, Integer size) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve all entities from database
            List<CreateInvoiceRequest> entities = createInvoiceRequestDomainRepository.findAll();
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("listInvoices")
                            .resource("CreateInvoiceRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("CreateInvoiceRequestDomainRepository")
                            .collection("invoice_billing_service_invoices")
                            .recordCount(entities.size())
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Step 1: Map persisted entities to the OpenAPI wrapper item DTOs
            List<Invoice> responses = entities.stream().map(this::mapToInvoice).collect(Collectors.toList());
            // Step 2: Create the OpenAPI list wrapper and populate its list property
            InvoiceListResponse response = new InvoiceListResponse();
            response.setContent(responses);
            // Step 3: Return the wrapper response required by the API contract
            return ResponseEntity.ok(response);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("listInvoices")
                            .resource("CreateInvoiceRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("CreateInvoiceRequestDomainRepository")
                            .collection("invoice_billing_service_invoices")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<Invoice> updateInvoice(String invoiceId,
            UpdateInvoiceRequest updateInvoiceRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // TODO: Implement custom business logic
            // Available repository methods:
            //   - save(entity) - Create or update
            //   - findById(id) - Find by ID
            //   - findAll() - Get all entities
            //   - existsById(id) - Check if exists
            //   - deleteById(id) - Delete by ID
            //   - count() - Count all entities
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("updateInvoice")
                            .resource("CreateInvoiceRequest")
                            .action("UNKNOWN")
                            .status("NOT_IMPLEMENTED")
                            .repository("CreateInvoiceRequestRepository")
                            .collection("invoice_billing_service_invoices")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            throw ApiException.notImplemented("Generated operation updateInvoice requires custom business logic");
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("updateInvoice")
                            .resource("CreateInvoiceRequest")
                            .action("UPDATE")
                            .status("FAILED")
                            .repository("CreateInvoiceRequestDomainRepository")
                            .collection("invoice_billing_service_invoices")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_update_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<Void> voidInvoice(String invoiceId) {
        long businessStartedAt = System.nanoTime();
        try {
            // TODO: Implement custom business logic
            // Available repository methods:
            //   - save(entity) - Create or update
            //   - findById(id) - Find by ID
            //   - findAll() - Get all entities
            //   - existsById(id) - Check if exists
            //   - deleteById(id) - Delete by ID
            //   - count() - Count all entities
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("voidInvoice")
                            .resource("CreateInvoiceRequest")
                            .action("UNKNOWN")
                            .status("NOT_IMPLEMENTED")
                            .repository("CreateInvoiceRequestRepository")
                            .collection("invoice_billing_service_invoices")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            throw ApiException.notImplemented("Generated operation voidInvoice requires custom business logic");
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("voidInvoice")
                            .resource("CreateInvoiceRequest")
                            .action("UNKNOWN")
                            .status("FAILED")
                            .repository("CreateInvoiceRequestDomainRepository")
                            .collection("invoice_billing_service_invoices")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("business_operation_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private String toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        return id.toString();
    }

    /**
     * Assigns a Mongo document ID when the generated model does not have one yet.
     */
    private void ensureEntityId(Object entity) {
        if (entity == null) {
            return;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object currentId = getter.invoke(entity);
            if (currentId == null || currentId.toString().isBlank()) {
                setEntityId(entity, UUID.randomUUID().toString());
            }
        } catch (Exception ignored) {
            // Generated models are enhanced with getId/setId; ignore if custom code removed them.
        }
    }

    private void setEntityId(Object entity, String id) {
        if (entity == null || id == null) {
            return;
        }
        try {
            Method setter = entity.getClass().getMethod("setId", String.class);
            setter.invoke(entity, id);
        } catch (Exception ignored) {
            // Generated models are enhanced with setId; ignore if custom code removed it.
        }
    }

    private String getEntityId(Object entity) {
        if (entity == null) {
            return null;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object value = getter.invoke(entity);
            return value != null ? value.toString() : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    private void copyGeneratedId(Object entity, Object response) {
        String id = getEntityId(entity);
        if (id == null || response == null) {
            return;
        }
        for (Method method : response.getClass().getMethods()) {
            if (method.getName().startsWith("set") && method.getName().endsWith("Id") && method.getParameterCount() == 1 && method.getParameterTypes()[0].equals(String.class)) {
                try {
                    method.invoke(response, id);
                    return;
                } catch (Exception ignored) {
                    // Try the next compatible ID setter.
                }
            }
        }
    }

    /**
     * Creates an empty response wrapper for list/search endpoints.
     */
    private <T> T emptyResponse(Class<T> responseType) {
        try {
            T response = responseType.getDeclaredConstructor().newInstance();
            for (Method method : responseType.getMethods()) {
                if (method.getName().startsWith("set") && method.getParameterCount() == 1 && List.class.isAssignableFrom(method.getParameterTypes()[0])) {
                    method.invoke(response, Collections.emptyList());
                }
            }
            return response;
        } catch (Exception ignored) {
            return null;
        }
    }

    /**
     * Calculates elapsed milliseconds for generated business operation logs.
     */
    private Long businessDurationMs(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000L;
    }

    /**
     * Maps CreateInvoiceRequest entity to Invoice response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private Invoice mapToInvoice(CreateInvoiceRequest entity) {
        // Create new response object
        Invoice response = new Invoice();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }

    /**
     * Maps CreateInvoiceRequest entity to InvoiceLineItem response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private InvoiceLineItem mapToInvoiceLineItem(CreateInvoiceRequest entity) {
        // Create new response object
        InvoiceLineItem response = new InvoiceLineItem();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
